# Generated by Django 4.2.23 on 2025-06-11 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_pdi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='data_criacao_conta',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
