# Generated by Django 4.2.23 on 2025-06-11 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdi_form', '0001_initial'),
        ('app_pdi', '0002_usuarios_data_criacao_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='pdi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pdi_form.pdi'),
            preserve_default=False,
        ),
    ]
