# Generated by Django 4.2.23 on 2025-06-11 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pdi', '0003_usuarios_pdi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='pdi',
        ),
    ]
