# Generated by Django 4.2.23 on 2025-06-18 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_pdi', '0005_w2hplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='w2hplan',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='planos_5w2h', to='app_pdi.usuarios'),
            preserve_default=False,
        ),
    ]
