# Generated by Django 5.2.2 on 2025-06-20 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('email', models.EmailField(max_length=254, verbose_name='')),
                ('senha', models.CharField(max_length=128)),
                ('data_criacao_conta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='W2HPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.TextField(blank=True, null=True)),
                ('why', models.TextField(blank=True, null=True)),
                ('who', models.TextField(blank=True, null=True)),
                ('when', models.TextField(blank=True, null=True)),
                ('where', models.TextField(blank=True, null=True)),
                ('how', models.TextField(blank=True, null=True)),
                ('howmuch', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_5w2h', to='app_pdi.usuarios')),
            ],
        ),
    ]
